### ISSUE TITLE
MSBuild.ExtensionPack.VisualStudio.TfsSource does not work with TFS2015

### ISSUE THREAD

**Issue by fabiostawinski** [mikefourie/MSBuildExtensionPack#63]
I have in my code the usage of the TfsSource, and when the server was migrated to TFS2015 the code below started failing:
<MSBuild.ExtensionPack.VisualStudio.TfsSource TaskAction="Checkout" ItemPath="$(ProjectDir)myfile.wxs" Version="2013" WorkingDirectory="$(SolutionRoot)" />

Error message:
Error : Exit Code 100. Nothing Succeeded: Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

It failed for task-based builds and XAML based builds.

**Comment by mikefourie** [comment]
Hi Fabio, I cant repo this. works fine for me. Are you sure the WorkingDirectory is correct?

**Comment by schenkjan** [comment]
@fabiostawinski @mikefourie : I'm having the exact same problem with TFS 2017.1 now, but it might be related to this issue here.
What I found out is, that tf.exe seems to have problems with workspaced that where created with a newer version of tf.exe.
So in @fabiostawinski 's case: TFS 2015's build agents create the workspace and the TfsSource task tries to do a checkout using a 2013 version of tf.exe
In my case TFS 2017.1 build agent creates the workspace and when the TfsSource task is called with version 2015 it does fail with exit code 100.
@fabiostawinski You could probably solve the problem by installing VisualStudio 2015 on your build machine and setting the Version property to 2015, so that TfsSource uses the same version of tf.exe as the build agent when creating the workspace.
In my case this doesn't work since MSBuild.ExtensionBack does not support Visual Studio 2017 yet.
@mikefourie Is it possible to influence the path to the used tf.exe other than providing the Version property?
